package model;

import java.sql.Date;

public class Book {
    private int id;
    private String title;
    private String author;
    private String ISBN;
    private String publisher;
    private Date publicationDate;
    private String description;
    private String genre;
    private double price;
    public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getISBN() {
		return ISBN;
	}

	public void setISBN(String iSBN) {
		ISBN = iSBN;
	}

	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getPublicationDate() {
		return publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getRating() {
		return rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	private int quantity;
    private int rating;
    private String image;

    // Constructors, getters, and setters

    // Constructor without id (assuming the id will be generated by the database)
    public Book(String title, String author, String ISBN, String publisher, Date publicationDate,
                String description, String genre, double price, int quantity, int rating, String image) {
        this.title = title;
        this.author = author;
        this.ISBN = ISBN;
        this.publisher = publisher;
        this.publicationDate = publicationDate;
        this.description = description;
        this.genre = genre;
        this.price = price;
        this.quantity = quantity;
        this.rating = rating;
        this.image = image;
    }
    
    public Book(int id, String title, String author, String ISBN, String publisher, Date publicationDate,
            String description, String genre, double price, int quantity, int rating, String image) {
    this.id = id;
    this.title = title;
    this.author = author;
    this.ISBN = ISBN;
    this.publisher = publisher;
    this.publicationDate = publicationDate;
    this.description = description;
    this.genre = genre;
    this.price = price;
    this.quantity = quantity;
    this.rating = rating;
    this.image = image;
}

    

}
